use gen_utils::error::Error;

pub fn run() -> Result<(), Error> {
    Ok(())
}
